# Generated by Django 3.1.7 on 2021-03-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Position', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MatchupsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlayerOne', to='rankingsApp.playermodel')),
                ('PlayerTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlayerTwo', to='rankingsApp.playermodel')),
                ('Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to='rankingsApp.playermodel')),
            ],
        ),
    ]
