# Generated by Django 3.1.7 on 2021-12-30 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankingsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=32)),
                ('Password', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='PlayerOne',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='PlayerTwo',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='Winner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Deviation',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Volatility',
        ),
        migrations.AddField(
            model_name='matchup',
            name='Result',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(default=1500)),
                ('Deviation', models.FloatField(default=500)),
                ('Volatility', models.FloatField(default=0.1)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankingsApp.player')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankingsApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='matchup',
            name='UserRanking1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserRanking1', to='rankingsApp.userranking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchup',
            name='UserRanking2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserRanking2', to='rankingsApp.userranking'),
            preserve_default=False,
        ),
    ]
