# Generated by Django 3.1.7 on 2021-03-20 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rankingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupsmodel',
            name='ComparisonDatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='Deviation',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='Rating',
            field=models.FloatField(default=1500),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='Volatility',
            field=models.FloatField(default=0.03),
        ),
    ]
