# Generated by Django 3.1.7 on 2021-08-22 04:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rankingsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Team', models.CharField(default='N/A', max_length=5)),
                ('Position', models.CharField(max_length=3)),
                ('Age', models.FloatField(default=200)),
                ('Birthdate', models.CharField(default=1900, max_length=10)),
                ('Draftyear', models.CharField(default=1900, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(default=1500)),
                ('Deviation', models.FloatField(default=100)),
                ('Volatility', models.FloatField(default=0.1)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player', to='rankingsApp.player')),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rankingsApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.BooleanField(default=None, null=True)),
                ('ComparisonDatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('PlayerOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlayerOne', to='rankingsApp.player')),
                ('PlayerTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlayerTwo', to='rankingsApp.player')),
                ('User', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rankingsApp.user')),
            ],
        ),
    ]
