# Generated by Django 3.1.7 on 2021-07-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Age',
            field=models.FloatField(default=200),
        ),
        migrations.AddField(
            model_name='player',
            name='Birthdate',
            field=models.CharField(default=1900, max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='Draftyear',
            field=models.CharField(default=1900, max_length=10),
        ),
    ]
