# Generated by Django 3.1.7 on 2021-03-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingsApp', '0002_auto_20210320_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchupsModel',
            new_name='MatchupModel',
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='Deviation',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='Volatility',
            field=models.FloatField(default=0.1),
        ),
    ]
