# Generated by Django 3.1.7 on 2021-09-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankingsApp', '0003_auto_20210904_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankingsApp.player'),
        ),
    ]
