# Generated by Django 3.1.7 on 2021-03-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingsApp', '0003_auto_20210321_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='Team',
            field=models.CharField(default='N/A', max_length=5),
        ),
    ]
